services:
  mongodb:
    image: mongo:7
    container_name: freela-cashflow-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: freela_cashflow
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
